workflows:
  ios-workflow:
    name: Inventory iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          # Futa lock file ili kuruhusu versions mpya zikubaliane
          rm -f pubspec.lock
          flutter pub get
      - name: Reset and Set Deployment Target to 15.0
        script: |
          rm -rf ios
          flutter create . --platforms=ios
          
          # Badilisha Deployment Target kuwa 15.0 kwenye Xcode project
          find ios/Runner.xcodeproj/project.pbxproj -type f -exec sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = [0-9][0-9]*\.[0-9]/IPHONEOS_DEPLOYMENT_TARGET = 15.0/g' {} +
          
          # MUHIMU: Update CocoaPods repos ili kupata matoleo yanayokubaliana
          cd ios
          pod repo update
      - name: Flutter build iOS
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app