workflows:
  ios-workflow:
    name: Inventory iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    working_directory: inventoryscanner
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          # Kama mradi upo ndani ya folder la inventoryscanner/inventoryscanner
          if [ -d "inventoryscanner" ]; then
            cd inventoryscanner
          fi
          flutter pub get
      - name: Flutter build iOS
        script: |
          if [ -d "inventoryscanner" ]; then
            cd inventoryscanner
          fi
          flutter build ios --release --no-codesign
    artifacts:
      - "**/build/ios/iphoneos/*.app"