workflows:
  ios-workflow:
    name: Inventory iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          # Lazimisha file_picker ya kisasa
          flutter pub add file_picker
          flutter pub get
      - name: Fix FilePicker Code and Reset iOS
        script: |
          # Hii script itafuta 'FilePicker.platform.' au 'FilePicker.instance.' 
          # na kuacha 'FilePicker.' pekee ambayo inakubalika kwenye matoleo mengi
          find . -name "*.dart" -exec sed -i '' 's/FilePicker\.platform\./FilePicker\./g' {} +
          find . -name "*.dart" -exec sed -i '' 's/FilePicker\.instance\./FilePicker\./g' {} +
          
          rm -rf ios
          flutter create . --platforms=ios
          flutter precache --ios
          
          # Force iOS 16.0
          find ios/Runner.xcodeproj/project.pbxproj -type f -exec sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = [0-9][0-9]*\.[0-9]/IPHONEOS_DEPLOYMENT_TARGET = 16.0/g' {} +
          
          # Safisha Podfile post_install
          sed -i '' '/post_install do |installer|/,$d' ios/Podfile
          echo "post_install do |installer|" >> ios/Podfile
          echo "  installer.pods_project.targets.each do |target|" >> ios/Podfile
          echo "    flutter_additional_ios_build_settings(target)" >> ios/Podfile
          echo "    target.build_configurations.each do |config|" >> ios/Podfile
          echo "      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'" >> ios/Podfile
          echo "      config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'" >> ios/Podfile
          echo "      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'i386 arm64'" >> ios/Podfile
          echo "    end" >> ios/Podfile
          echo "  end" >> ios/Podfile
          echo "end" >> ios/Podfile
          
          cd ios && pod install --repo-update
      - name: Flutter build iOS (Simulator)
        script: |
          flutter build ios --debug --simulator
    artifacts:
      - build/ios/iphonesimulator/*.app