workflows:
  ios-workflow:
    name: Inventory iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          rm -f pubspec.lock
          flutter pub get
      - name: Reset and Set Deployment Target to 16.0
        script: |
          # Futa na tengeneza folder la ios upya
          rm -rf ios
          flutter create . --platforms=ios
          
          # Hii ni muhimu ili kuzuia kosa la Podfile kule Codemagic
          flutter precache --ios
          
          # Kulazimisha iOS 16.0 kila mahali
          find ios/Runner.xcodeproj/project.pbxproj -type f -exec sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = [0-9][0-9]*\.[0-9]/IPHONEOS_DEPLOYMENT_TARGET = 16.0/g' {} +
          
          # Sasisha vyanzo vya CocoaPods
          cd ios && pod repo update
      - name: Flutter build iOS (Simulator)
        script: |
          # MUHIMU: Tunatumia --debug kwa simulator ili build isifeli
          flutter build ios --debug --simulator
    artifacts:
      - build/ios/iphonesimulator/*.app