workflows:
  ios-workflow:
    name: Inventory iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          rm -f pubspec.lock
          flutter pub get
      - name: Reset and Set Deployment Target to 16.0
        script: |
          rm -rf ios
          flutter create . --platforms=ios
          
          # Badilisha kila namba ya version iliyopo kuwa 16.0
          find ios/Runner.xcodeproj/project.pbxproj -type f -exec sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = [0-9][0-9]*\.[0-9]/IPHONEOS_DEPLOYMENT_TARGET = 16.0/g' {} +
          
          # Hakikisha hata faili la kusanidi Pods linajua ni 16.0
          if [ -f ios/Runner/Info.plist ]; then
            sed -i '' 's/12.0/16.0/g' ios/Runner/Info.plist
            sed -i '' 's/13.0/16.0/g' ios/Runner/Info.plist
            sed -i '' 's/14.0/16.0/g' ios/Runner/Info.plist
            sed -i '' 's/15.0/16.0/g' ios/Runner/Info.plist
            sed -i '' 's/15.5/16.0/g' ios/Runner/Info.plist
          fi
          
          cd ios && pod repo update
      - name: Flutter build iOS
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      - build/ios/iphoneos/*.app