workflows:
  ios-workflow:
    name: Inventory iOS Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    working_directory: inventoryscanner
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Flutter build iOS
        script: |
          flutter build ios --release --no-codesign
    artifacts:
      # Tumeongeza 'inventoryscanner/' hapa mbele
      - inventoryscanner/build/ios/iphoneos/*.app