workflows:
  android-workflow:
    name: Inventory Android Build
    max_build_duration: 60
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Build Android APK
        script: |
          # Jenga APK ya Release
          flutter build apk --release --build-name=1.1.72 --build-number=72
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - mlyukakenedy@gmail.com