name: INVENTORY_BUILD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_ios:
    name: Build iOS App
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.19.0
          cache: true

      - name: Install Dependencies
        # Tumesema 'cd inventoryscanner' hapa ili iingie kwenye folder sahihi
        run: |
          cd inventoryscanner
          flutter pub get

      - name: Build iOS App (No Codesign)
        run: |
          cd inventoryscanner
          flutter build ios --release --no-codesign \
          --obfuscate --split-debug-info=build/ios/symbols

      - name: Package iOS App
        run: |
          cd inventoryscanner/build/ios/iphoneos
          mkdir -p Payload
          cp -r Runner.app Payload/
          zip -r ../../../inventory_ios_build.zip Payload

      - name: Upload iOS Build
        uses: actions/upload-artifact@v4
        with:
          name: Inventory-iOS-App
          path: inventory_ios_build.zip
          retention-days: 7

  build_android:
    name: Build Android App
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.19.0
          cache: true

      - name: Install Dependencies
        run: |
          cd inventoryscanner
          flutter pub get

      - name: Build Android APK
        run: |
          cd inventoryscanner
          flutter build apk --release

      - name: Upload Android Build
        uses: actions/upload-artifact@v4
        with:
          name: Inventory-Android-App
          path: inventoryscanner/build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7