platform :ios, '15.0'

# Inasaidia kuzuia matatizo ya "paths" na "input/output" kule Codemagic
install! 'cocoapods', :disable_input_output_paths => true

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Badala ya kutumia flutter_install_all_ios_pods,
  # CocoaPods itazisoma plugins kupitia symlinks otomatiki
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    # Hii inalazimisha kila plugin (app_links, firebase, n.k.) itumie iOS 15.0
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end