platform :ios, '15.0'

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Badala ya kutafuta flutter_tools, tunaitafuta app_links moja kwa moja
  # Hii inalazimisha CocoaPods kuiona plugin hata kama Flutter podhelper imefeli
  pod 'app_links', :path => File.join('..', '.symlinks', 'plugins', 'app_links', 'ios')

  # Ikiwa unatumia Firebase, ongeza na hii:
  pod 'firebase_core', :path => File.join('..', '.symlinks', 'plugins', 'firebase_core', 'ios')
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end